<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shahnozas-MacBook-Air.local" failures="1" tests="3" name="TestNGFrameworkB1" time="8.038" errors="0" timestamp="2023-02-22T19:34:01 MST">
  <testcase classname="com.exelenter.testcases.LoginTest" name="validAdminLogin" time="0.955"/>
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserEmptyPassword" time="0.13">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.exelenter.testcases.LoginTest.validUserEmptyPassword(LoginTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validUserEmptyPassword -->
  <testcase classname="com.exelenter.testcases.LoginTest" name="validUserInvalidPassword" time="0.0">
    <skipped/>
  </testcase> <!-- validUserInvalidPassword -->
</testsuite> <!-- TestNGFrameworkB1 -->
